### ISSUE TITLE
Program does not run in the backround and tries to capture the mouse cursor

### ISSUE THREAD

**Issue by Isaiahh146** [Isaiahh146/Oculus-Link-Passthrough-Home#2]
This will most likely be fixed with the next update, I'm not that skilled so it might take a while to figure this out

**Comment by najak3d** [comment]
I love the app here - it does the job.

BUT this "capturing of Cursor" is a critical stopper.   I hope you can fix this ASAP, otherwise, I can't use it.

I really really love the ability for "Pass Through" while debugging Unity3D apps.

Can you give us an ETA for this? (or if TBD/unknown, please let us know that too)

**Comment by Isaiahh146** [comment]
It should be a relatively easy fix, might be a while before I get to it though due to work and school

**Comment by Isaiahh146** [comment]
The issue has been fixed with the most recent version, the app no longer tries to capture the mouse cursor.

**Comment by najak3d** [comment]
Thank you!   I'll give it another try soon.  For the moment, I've switched off of VR apps, and back onto a normal Unity Non-VR game app.
